<a href="https://colab.research.google.com/github/syedaftab-dev/Backend_dev_resources/blob/main/1_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NLP intuition with ML

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df=pd.read_csv('train.txt',sep=';',header=None,names=['text','emotion'])

csv main comma separated hothe value par ismain ; colan hai,aur names=column names given there it self

In [ ]:
df.head()

text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [ ]:
# converting to numbers

In [ ]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [ ]:
unique_emotions = df['emotion'].unique()

array([0, 1, 2, 3, 4, 5])

In [ ]:
emotion_numbers = {}
i=0
for emo in unique_emotions:
  emotion_numbers[emo]=i
  i+=1

In [ ]:
df['emotion']=df['emotion'].map(emotion_numbers)

When `df['emotion'].map(emotion_numbers)` is executed, for each value in the `emotion` column:

1.  The `map()` function looks up the current emotion string (e.g., 'sadness', 'anger') in the `emotion_numbers` dictionary.
2.  It then replaces that emotion string with its corresponding numerical value found in the dictionary (e.g., 'sadness' becomes `0`, 'anger' becomes `1`).

So, the dictionary `emotion_numbers` is the crucial link that defines *which* number replaces *which* word.

## Do cleaning as mention in notebook

In [ ]:
# convert to lowercase
df['text']=df['text'].apply(lambda x:x.lower())

In [ ]:
# removing punctuations like , . ? @ # $ %
import string
def remove_punc(txt):
  return txt.translate(str.maketrans('','',string.punctuation))

### str.maketrans(string,replace string with,delete that string)
### string.punctuation -> contains all punctuations
### here  str.maketrans('','',string.punctuation) - no replacemnt just delete the punctuations

In [ ]:
df['text']=df['text'].apply(remove_punc)

In [ ]:
# removing numbers
def remove_numbers(txt):
  new=""
  for i in txt:
    if not i.isdigit():
      new+=i
  return new
# take a sentence everytime and considering
# word by word ,finding any
# digit in that word then not including that
# word in new framed sentence

In [ ]:
df['text']=df['text'].apply(remove_numbers)

In [ ]:
# Remove URls and Links
# same function as above
#and when we get https,// then remove that

In [ ]:
# Removing Emojis and special symbols


# using ASCII Values - we know ascii
# values of characters and not of emojis
# so ignore them

def remove_emojis(txt):
  new=""
  for i in txt:
    if i.isascii(): # ascii values exist or not
      new+=i
  return new


In [ ]:
# Removing Stopwords - remove in NLP and keep in Deeplearning accordingly

import nltk #natural language toolkit
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
# download these
nltk.download('stopwords') # stopword hai ismain
nltk.download('punkt')# for tokenization

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
stop_words=set(stopwords.words('english'))#getting english stopwords from stopwords library

In [ ]:
def remove(txt):
    words = txt.split() # or words_tokenize(txt)
    cleaned=[]
    for i in words:
      if i not in stop_words:
        cleaned.append(i)
    return " ".join(cleaned)

In [ ]:
df['text']=df['text'].apply(remove)

In [ ]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

## BAG OF WORDS IMPLEMENTATION(feature extraction)
refer the sklearn page for this before using
## CountVectorizer
### class sklearn.feature_extraction.text.CountVectorizer(*, input='content', encoding='utf-8', decode_error='strict', strip_accents=None, lowercase=True, preprocessor=None, tokenizer=None, stop_words=None, token_pattern='(?u)\\b\\w\\w+\\b', ngram_range=(1, 1), analyzer='word', max_df=1.0, min_df=1, max_features=None, vocabulary=None, binary=False, dtype=<class 'numpy.int64'>)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

documents=[
    "I love pizza",
    "Pizza is the best",
    "I love pasta",
    "Pasta is great"
]

# n_gram default (1,1) = unigram
vectorizer=CountVectorizer(ngram_range=(3,3))
X=vectorizer.fit_transform(documents)

print("vocabulary",vectorizer.get_feature_names_out())
print("\nBow Matrix:\n",X.toarray())

vocabulary ['is the best' 'pasta is great' 'pizza is the']

Bow Matrix:
 [[0 0 0]
 [1 0 1]
 [0 0 0]
 [0 1 0]]


## TF - IDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

documents=[
    "I love pizza",
    "Pizza is the best",
    "I love pasta",
    "Pasta is great"
]

# n_gram default (1,1) = unigram
vectorizer=TfidfVectorizer()
X=vectorizer.fit_transform(documents)

print("vocabulary",vectorizer.get_feature_names_out())
print("\nBow Matrix:\n",X.toarray())

vocabulary ['best' 'great' 'is' 'love' 'pasta' 'pizza' 'the']

Bow Matrix:
 [[0.         0.         0.         0.70710678 0.         0.70710678
  0.        ]
 [0.55528266 0.         0.43779123 0.         0.         0.43779123
  0.55528266]
 [0.         0.         0.         0.70710678 0.70710678 0.
  0.        ]
 [0.         0.66767854 0.52640543 0.         0.52640543 0.
  0.        ]]


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df['text'],df['emotion'],test_size=0.33,random_state=42)

In [ ]:
X_train.shape

(10720,)

In [ ]:
X_test.shape

(5280,)

# Converting text to vectors




In [ ]:
X_train

8917     feeling quite pleased fact one coupon use grocery
9453               stressed finally come end feel relieved
2829     feel blessed know immense family supporters co...
9681                       didnt feel like missed anything
12246            feel listless unable imagine ever working
                               ...                        
13418    love leave reader feeling confused slightly de...
5390                                         feel delicate
860                          starting feel little stressed
15795             feel stressed tired worn shape neglected
7270         feel someone rude wrongly done something lose
Name: text, Length: 10720, dtype: object

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer

# 1st bag of word technique

In [ ]:
#using bagof words
bow_vectorizer = CountVectorizer()

In [ ]:
X_train_bow = bow_vectorizer.fit_transform(X_train)

In [ ]:
X_test_bow = bow_vectorizer.transform(X_test)

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

In [ ]:
nb_model = MultinomialNB()
nb_model.fit(X_train_bow, y_train)

MultinomialNB()

In [ ]:
pred_nb = nb_model.predict(X_test_bow)

In [ ]:
print(accuracy_score(y_test, pred_nb))

0.7647727272727273


# Using TFIDF vectorization

In [ ]:
tfidf_vectorizer = TfidfVectorizer()

In [ ]:
X_train_tfidf=tfidf_vectorizer.fit_transform(X_train)

In [ ]:
X_test_tfidf=tfidf_vectorizer.transform(X_test)

In [ ]:
nb2_model = MultinomialNB()
nb2_model.fit(X_train_tfidf, y_train)

MultinomialNB()

In [ ]:
pred_tfidf = nb2_model.predict(X_test_tfidf)

In [ ]:
print(accuracy_score(pred_tfidf,y_test))

0.6606060606060606


# using logistic regression

In [ ]:
from sklearn.linear_model import LogisticRegression
# max iteration 1000 liyo good for large text
lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(X_train_tfidf, y_train)

LogisticRegression(max_iter=1000)

In [ ]:
pred_lr=lr_model.predict(X_test_tfidf)

In [ ]:
print(accuracy_score(y_test,pred_lr))

0.8081439393939394
